name: CI

on:
  push:
    branches:
      - master
  pull_request:
  release:
    types: [published]

env:
  CARGO_TERM_COLOR: always

jobs:
  publish:
    # Only do this job if publishing a release
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Publish crate
      uses: katyo/publish-crates@v1
      with:
          path: 'fuels-contract/'
          check-repo: false
          dry-run: true
          args: --no-verify
          registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
